services:
  postgres:
    image: postgres:17
    container_name: order-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: orders
      TZ: Europe/Kyiv
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: